name: anime_fandom
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=2.19.5 <3.0.0'

dependencies:
  change_app_package_name: ^1.1.0
  dio: ^5.1.1
  dropdown_button2: ^1.9.2
  firebase_auth: ^4.2.2
  firebase_core: ^2.10.0
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.3.5
  flutter_screenutil: ^5.7.0
  hive_flutter: ^1.1.0
  pinput: ^2.2.31
  provider: ^6.0.5
  syncfusion_flutter_datepicker: ^21.1.41
  timelines: ^0.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: Manrope
      fonts:
        - asset: assets/fonts/Manrope-Regular.ttf
        - asset: assets/fonts/Manrope-Bold.ttf
        - asset: assets/fonts/Manrope-ExtraBold.ttf
        - asset: assets/fonts/Manrope-SemiBold.ttf
        - asset: assets/fonts/Manrope-Light.ttf
        - asset: assets/fonts/Manrope-ExtraLight.ttf
        - asset: assets/fonts/Manrope-Medium.ttf

    - family: Inter
      fonts:
        - asset: assets/fonts/Inter-Regular.ttf
        - asset: assets/fonts/Inter-Bold.ttf
        - asset: assets/fonts/Inter-ExtraBold.ttf
        - asset: assets/fonts/Inter-SemiBold.ttf
        - asset: assets/fonts/Inter-Light.ttf
        - asset: assets/fonts/Inter-ExtraLight.ttf
        - asset: assets/fonts/Inter-Medium.ttf
        - asset: assets/fonts/Inter-Black.ttf
        - asset: assets/fonts/Inter-Thin.ttf

    - family: SF-Pro
      fonts:
        - asset: assets/fonts/SF-Pro.ttf
