// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD0PS1vYt1eG-6IFgZCVg07B7t34j5cNio',
    appId: '1:553795253125:web:68a11a95a20d9faa90caec',
    messagingSenderId: '553795253125',
    projectId: 'bong-anime-fandom',
    authDomain: 'bong-anime-fandom.firebaseapp.com',
    storageBucket: 'bong-anime-fandom.appspot.com',
    measurementId: 'G-7CTE0GB14G',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDrfZaKcfWIGEb7FnkIhf_9Nv0tLLEqkkI',
    appId: '1:553795253125:android:1f6ec554f1e8b3fe90caec',
    messagingSenderId: '553795253125',
    projectId: 'bong-anime-fandom',
    storageBucket: 'bong-anime-fandom.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBk32B6hjWLxWEAOfrKWt9q_3HdXw0kk4c',
    appId: '1:553795253125:ios:1cad8a923210582f90caec',
    messagingSenderId: '553795253125',
    projectId: 'bong-anime-fandom',
    storageBucket: 'bong-anime-fandom.appspot.com',
    iosClientId: '553795253125-r2h5c7v9o8ig7pfu7i0q27f0sa4sq6ba.apps.googleusercontent.com',
    iosBundleId: 'com.example.animeFandom',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBk32B6hjWLxWEAOfrKWt9q_3HdXw0kk4c',
    appId: '1:553795253125:ios:1cad8a923210582f90caec',
    messagingSenderId: '553795253125',
    projectId: 'bong-anime-fandom',
    storageBucket: 'bong-anime-fandom.appspot.com',
    iosClientId: '553795253125-r2h5c7v9o8ig7pfu7i0q27f0sa4sq6ba.apps.googleusercontent.com',
    iosBundleId: 'com.example.animeFandom',
  );
}
